export const REGISTRATION_INPUT_CHANGE = 'REGISTRATION/INPUT_CHANGE';
export const REGISTRATION_DATE_OF_BIRTH_CHANGE = 'REGISTRATION/DATE_OF_BIRTH_CHANGE';
export const REGISTRATION_SUCCESS = 'REGISTRATION/REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION/REGISTRATION_ERROR';

export const PROFILE_SHOW_LOADING = 'USER_PROFILE/PROFILE_SHOW_LOADING';
export const PROFILE_LOAD_SUCCESS = 'USER_PROFILE/PROFILE_LOAD_SUCCESS';
export const PROFILE_LOAD_ERROR = 'USER_PROFILE/PROFILE_LOAD_ERROR';
export const PROFILE_POSTS_LOAD_SUCCESS = 'USER_PROFILE/PROFILE_POSTS_LOAD_SUCCESS';
