export const REGISTRATION_INPUT_CHANGE = 'REGISTRATION/INPUT_CHANGE';
export const REGISTRATION_DATE_OF_BIRTH_CHANGE = 'REGISTRATION/DATE_OF_BIRTH_CHANGE';
export const REGISTRATION_SUCCESS = 'REGISTRATION/REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION/REGISTRATION_ERROR';
