export const REGISTRATION_INPUT_CHANGE = 'REGISTRATION/INPUT_CHANGE';
export const REGISTRATION_DATE_OF_BIRTH_CHANGE = 'REGISTRATION/DATE_OF_BIRTH_CHANGE';
export const REGISTRATION_SUCCESS = 'REGISTRATION/REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION/REGISTRATION_ERROR';

export const PROFILE_SHOW_LOADING = 'USER_PROFILE/PROFILE_SHOW_LOADING';
export const PROFILE_LOAD_SUCCESS = 'USER_PROFILE/PROFILE_LOAD_SUCCESS';
export const PROFILE_LOAD_ERROR = 'USER_PROFILE/PROFILE_LOAD_ERROR';
export const PROFILE_POSTS_LOAD_SUCCESS = 'USER_PROFILE/PROFILE_POSTS_LOAD_SUCCESS';
export const PROFILE_UPDATE_DATA_SUCCESS = 'USER_PROFILE/PROFILE_UPDATE_DATA';
export const SET_SHOW_MODAL_EDIT_PROFILE = 'USER_PROFILE/SET_SHOW_MODAL_EDIT_PROFILE';

export const USER_LIST_SHOW_LOADING = 'USER_LIST/USER_LIST_SHOW_LOADING';
export const USER_LIST_SUCCESS = 'USER_LIST/USER_LIST_SUCCESS';

export const POST_LIST_LOAD_SUCCESS = 'POST_LIST/POST_LIST_LOAD_SUCCESS';

export const POST_MODAL_SHOW_MODAL = 'MODAL_POST/MODAL_POST_SHOW_MODAL';
export const POST_MODAL_SHOW_COMMENTS = 'MODAL_POST/MODAL_POST_SHOW_COMMENTS';
export const POST_MODAL_HIDE_MODAL = 'MODAL_POST/POST_MODAL_HIDE_MODAL';
